// Conference accounts configuration
export const CONFERENCE_ACCOUNTS = [
    {
        username: 'LIUTEXSUMMIT2026',
        email: process.env.LIUTEX_EMAIL || 'liutex@sciengasummits.com',
        conferenceId: 'liutex',
        displayName: 'LIUTEX SUMMIT 2026',
    },
    {
        username: 'FOODAGRISUMMIT2026',
        email: process.env.FOODAGRI_EMAIL || 'foodagri@sciengasummits.com',
        conferenceId: 'foodagri',
        displayName: 'FOOD AGRI SUMMIT 2026',
    },
    {
        username: 'FLUIDMECHSUMMIT2026',
        email: process.env.FLUID_EMAIL || 'fluid@sciengasummits.com',
        conferenceId: 'fluid',
        displayName: 'FLUID MECHANICS & TURBOMACHINERY 2026',
    },
    {
        username: 'RENEWABLECLISUMMIT2026',
        email: process.env.RENEWABLE_EMAIL || 'renewable@sciengasummits.com',
        conferenceId: 'renewable',
        displayName: 'RENEWABLE ENERGY & CLIMATE CHANGE 2026',
    },
    {
        username: 'CYBERQUANTUMSUMMIT2026',
        email: process.env.CYBER_EMAIL || 'contact@cyberquantumsummit.com',
        conferenceId: 'cyber',
        displayName: 'CYBERSECURITY & QUANTUM COMPUTING 2026',
    },
    {
        username: 'POWERENGSUMMIT2026',
        email: process.env.POWERENG_EMAIL || 'contact@powerenergysummit.com',
        conferenceId: 'powereng',
        displayName: 'POWER ENERGY & ELECTRICAL ENGINEERING 2026',
    },
];

// Conference config for frontend
export const CONFERENCE_CONFIG = {
    liutex: {
        conferenceId: 'liutex',
        displayName: 'LIUTEX VORTEX SUMMIT 2026',
        shortName: 'LIUTEX SUMMIT',
        logoText: 'LV',
        logoSub: 'Summit',
        brandTop: 'LIUTEX',
        brandSub: 'VORTEX SUMMIT',
        footerText: '© Copyright 2026 LIUTEX SUMMIT.',
        accentColor: '#6366f1',
        accentGlow: 'rgba(99,102,241,0.35)',
    },
    foodagri: {
        conferenceId: 'foodagri',
        displayName: 'FOOD AGRI SUMMIT 2026',
        shortName: 'FOOD AGRI SUMMIT',
        logoText: 'FA',
        logoSub: 'Summit',
        brandTop: 'FOOD AGRI',
        brandSub: 'SUMMIT 2026',
        footerText: '© Copyright 2026 FOOD AGRI SUMMIT.',
        accentColor: '#16a34a',
        accentGlow: 'rgba(22,163,74,0.35)',
    },
    fluid: {
        conferenceId: 'fluid',
        displayName: 'FLUID MECHANICS & TURBOMACHINERY 2026',
        shortName: 'FLUID SUMMIT',
        logoText: 'FM',
        logoSub: 'Summit',
        brandTop: 'FLUID MECHANICS',
        brandSub: '& TURBOMACHINERY',
        footerText: '© Copyright 2026 FLUID MECHANICS & TURBOMACHINERY SUMMIT.',
        accentColor: '#0891b2',
        accentGlow: 'rgba(8,145,178,0.35)',
    },
    renewable: {
        conferenceId: 'renewable',
        displayName: 'RENEWABLE ENERGY & CLIMATE CHANGE 2026',
        shortName: 'RENEWABLE CLI SUMMIT',
        logoText: 'RE',
        logoSub: 'Summit',
        brandTop: 'RENEWABLE ENERGY',
        brandSub: '& CLIMATE CHANGE',
        footerText: '© Copyright 2026 RENEWABLE ENERGY & CLIMATE CHANGE SUMMIT.',
        accentColor: '#16a34a',
        accentGlow: 'rgba(22,163,74,0.35)',
    },
    cyber: {
        conferenceId: 'cyber',
        displayName: 'CYBERSECURITY & QUANTUM COMPUTING 2026',
        shortName: 'CYBERQUANTUM SUMMIT',
        logoText: 'CQ',
        logoSub: 'Summit',
        brandTop: 'CYBERQUANTUM',
        brandSub: 'SUMMIT 2026',
        footerText: '© Copyright 2026 CYBERQUANTUM SUMMIT.',
        accentColor: '#2563eb',
        accentGlow: 'rgba(37,99,235,0.35)',
    },
    powereng: {
        conferenceId: 'powereng',
        displayName: 'POWER ENERGY & ELECTRICAL ENGINEERING 2026',
        shortName: 'POWERENG SUMMIT',
        logoText: 'PE',
        logoSub: 'Summit',
        brandTop: 'POWER ENERGY',
        brandSub: '& ELECTRICAL ENG.',
        footerText: '© Copyright 2026 POWER ENERGY & ELECTRICAL ENGINEERING SUMMIT.',
        accentColor: '#d97706',
        accentGlow: 'rgba(217,119,6,0.35)',
    },
};
