// Conference accounts configuration
export const CONFERENCE_ACCOUNTS = [
    {
        username: 'LIUTEXSUMMIT2026',
        aliases: ['LIUTEX2026'],
        email: process.env.LIUTEX_EMAIL || 'liutex@sciengasummits.com',
        conferenceId: 'liutex',
        displayName: 'LIUTEX SUMMIT 2026',
    },
    {
        username: 'FOODAGRISUMMIT2026',
        aliases: ['FOODAGRI2026'],
        email: process.env.FOODAGRI_EMAIL || 'foodagri@sciengasummits.com',
        conferenceId: 'foodagri',
        displayName: 'FOOD AGRI SUMMIT 2026',
    },
    {
        username: 'FLUIDMECHSUMMIT2026',
        aliases: ['FLUIDMECH2026'],
        email: process.env.FLUID_EMAIL || 'fluid@sciengasummits.com',
        conferenceId: 'fluid',
        displayName: 'FLUID MECHANICS & TURBOMACHINERY 2026',
    },
    {
        username: 'RENEWABLECLISUMMIT2026',
        aliases: ['RENEWABLECLI2026', 'RENEWABLE2026'],
        email: process.env.RENEWABLE_EMAIL || 'renewable@sciengasummits.com',
        conferenceId: 'renewable',
        displayName: 'RENEWABLE ENERGY & CLIMATE CHANGE 2026',
    },
    {
        username: 'CYBERQUANTUMSUMMIT2026',
        aliases: ['CYBERQUANTUM2026'],
        email: process.env.CYBER_EMAIL || 'contact@cyberquantumsummit.com',
        conferenceId: 'cyber',
        displayName: 'CYBERSECURITY & QUANTUM COMPUTING 2026',
    },
    {
        username: 'POWERENGSUMMIT2026',
        aliases: ['POWERENG2026'],
        email: process.env.POWERENG_EMAIL || 'contact@powerenergysummit.com',
        conferenceId: 'powereng',
        displayName: 'POWER ENERGY & ELECTRICAL ENGINEERING 2026',
    },
    {
        username: 'IQCE2027',
        aliases: ['IQCES2027', 'IQCE2027SUMMIT'],
        email: process.env.IQCE2027_EMAIL || process.env.IQCES_EMAIL || 'quantumengineering@sciengasummits.com',
        conferenceId: 'iqce2027',
        displayName: 'QUANTUM COMPUTING & ENGINEERING SUMMIT 2027',
    },
    {
        username: 'ICOGWHSUMMIT2027',
        aliases: ['ICOGWH2027'],
        email: process.env.ICOGWH_EMAIL || 'obstetrics@sciengasummits.com',
        conferenceId: 'icogwh',
        displayName: 'OBSTETRICS, GYNECOLOGY AND WOMEN HEALTH 2027',
    },
    {
        username: 'ICEMMAE2027',
        aliases: ['ICEMMAE2027SUMMIT'],
        email: process.env.ICEMMAE_EMAIL || 'icemmae@sciengasummits.com',
        conferenceId: 'icemmae2027',
        displayName: 'MECHANICAL, MECHATRONICS AND AEROSPACE ENGINEERING 2027',
    },
    {
        username: 'POLYMATSUMMIT2026',
        aliases: ['POLYMAT2026'],
        email: process.env.POLYMAT_EMAIL || 'polymat@sciengasummits.com',
        conferenceId: 'polymat',
        displayName: 'ANNUAL INTERNATIONAL CONFERENCE ON POLYMERS AND COMPOSITE MATERIALS 2026',
    },
    {
        username: 'ADVANCENANOSUMMIT2026',
        aliases: ['ADVANCENANO2026'],
        email: process.env.ADVANCENANO_EMAIL || 'advancenanosummit@sciengasummits.com',
        conferenceId: 'advancenano',
        displayName: 'ADVANCE NANO SUMMIT 2026',
    },
    {
        username: 'OPTICPHOTONSUMMIT2026',
        aliases: ['OPTICPHOTON2026'],
        email: process.env.OPTIC_EMAIL || 'opticphotosummit@sciengasummits.com',
        conferenceId: 'opticphoton',
        displayName: 'OPTIC PHOTON SUMMIT 2026',
    },
    {
        username: 'CROPSCIENGSUMMIT2026',
        aliases: ['CROPSCIENG2026'],
        email: process.env.CROPSCIENG_EMAIL || 'cropsciengasummits@sciengasummits.com',
        conferenceId: 'cropscieng',
        displayName: 'CROP SCIENCE AND ENGINEERING 2026',
    },
    {
        username: 'CLEANENGTECHSUMMIT2026',
        aliases: ['CLEANENGTECH2026'],
        email: process.env.CLEANENG_EMAIL || 'cleanengtech@sciengasummits.com',
        conferenceId: 'cleaneng',
        displayName: 'CLEAN ENERGY & SUSTAINABLE TECHNOLOGIES 2026',
    },
    {
        username: 'HEALTHMEDSUMMIT2026',
        aliases: ['HEALTHMED2026'],
        email: process.env.HEALTHMED_EMAIL || 'healthmedsummit@sciengasummits.com',
        conferenceId: 'healthmed',
        displayName: 'HEALTH MED SUMMIT 2026',
    },
    {
        username: 'ASTROSPACESUMMIT2026',
        aliases: ['ASTROSPACE2026'],
        email: process.env.ASTRO_EMAIL || 'astrospace@sciengasummits.com',
        conferenceId: 'astrospace',
        displayName: 'ASTRO SPACE SUMMIT 2026',
    },
    {
        username: 'CONDENSEDPHYSSUMMIT2026',
        aliases: ['CONDENSEDPHYS2026'],
        email: process.env.CONDENSEDPHYS_EMAIL || 'condensedphyssummit2026@sciengasummits.com',
        conferenceId: 'condensedphys',
        displayName: 'CONDENSED MATTER PHYSICS SUMMIT 2026',
    },
    {
        username: 'AIROBOTSML2027',
        aliases: ['AIROBOTSML2027', 'AIROBOTS2027'],
        email: process.env.AIROBOTSML_EMAIL || 'airobotsml@sciengasummits.com',
        conferenceId: 'airobotsml',
        displayName: 'AI ROBOTS & MACHINE LEARNING SUMMIT 2027',
    },
];

// Conference config for frontend
export const CONFERENCE_CONFIG = {
    liutex: {
        conferenceId: 'liutex',
        displayName: 'LIUTEX VORTEX SUMMIT 2026',
        shortName: 'LIUTEX SUMMIT',
        logoText: 'LV',
        logoSub: 'Summit',
        brandTop: 'LIUTEX',
        brandSub: 'VORTEX SUMMIT',
        footerText: '© Copyright 2026 LIUTEX SUMMIT.',
        email: 'liutex@sciengasummits.com',
        accentColor: '#6366f1',
        accentGlow: 'rgba(99,102,241,0.35)',
    },
    foodagri: {
        conferenceId: 'foodagri',
        displayName: 'FOOD AGRI SUMMIT 2026',
        shortName: 'FOOD AGRI SUMMIT',
        logoText: 'FA',
        logoSub: 'Summit',
        brandTop: 'FOOD AGRI',
        brandSub: 'SUMMIT 2026',
        footerText: '© Copyright 2026 FOOD AGRI SUMMIT.',
        email: 'foodagri@sciengasummits.com',
        accentColor: '#16a34a',
        accentGlow: 'rgba(22,163,74,0.35)',
    },
    fluid: {
        conferenceId: 'fluid',
        displayName: 'FLUID MECHANICS & TURBOMACHINERY 2026',
        shortName: 'FLUID SUMMIT',
        logoText: 'FM',
        logoSub: 'Summit',
        brandTop: 'FLUID MECHANICS',
        brandSub: '& TURBOMACHINERY',
        footerText: '© Copyright 2026 FLUID MECHANICS & TURBOMACHINERY SUMMIT.',
        email: 'fluid@sciengasummits.com',
        accentColor: '#0891b2',
        accentGlow: 'rgba(8,145,178,0.35)',
    },
    renewable: {
        conferenceId: 'renewable',
        displayName: 'RENEWABLE ENERGY & CLIMATE CHANGE 2026',
        shortName: 'RENEWABLE CLI SUMMIT',
        logoText: 'RE',
        logoSub: 'Summit',
        brandTop: 'RENEWABLE ENERGY',
        brandSub: '& CLIMATE CHANGE',
        footerText: '© Copyright 2026 RENEWABLE ENERGY & CLIMATE CHANGE SUMMIT.',
        email: 'renewable@sciengasummits.com',
        accentColor: '#16a34a',
        accentGlow: 'rgba(22,163,74,0.35)',
    },
    cyber: {
        conferenceId: 'cyber',
        displayName: 'CYBERSECURITY & QUANTUM COMPUTING 2026',
        shortName: 'CYBERQUANTUM SUMMIT',
        logoText: 'CQ',
        logoSub: 'Summit',
        brandTop: 'CYBERQUANTUM',
        brandSub: 'SUMMIT 2026',
        footerText: '© Copyright 2026 CYBERQUANTUM SUMMIT.',
        email: 'contact@cyberquantumsummit.com',
        accentColor: '#2563eb',
        accentGlow: 'rgba(37,99,235,0.35)',
    },
    powereng: {
        conferenceId: 'powereng',
        displayName: 'POWER ENERGY & ELECTRICAL ENGINEERING 2026',
        shortName: 'POWERENG SUMMIT',
        logoText: 'PE',
        logoSub: 'Summit',
        brandTop: 'POWER ENERGY',
        brandSub: '& ELECTRICAL ENG.',
        footerText: '© Copyright 2026 POWER ENERGY & ELECTRICAL ENGINEERING SUMMIT.',
        email: 'contact@powerenergysummit.com',
        accentColor: '#d97706',
        accentGlow: 'rgba(217,119,6,0.35)',
    },
    iqce2027: {
        conferenceId: 'iqce2027',
        displayName: 'QUANTUM COMPUTING & ENGINEERING SUMMIT 2027',
        shortName: 'IQCE 2027',
        logoText: 'QC',
        logoSub: 'Summit',
        brandTop: 'QUANTUM COMPUTING',
        brandSub: '& ENGINEERING 2027',
        footerText: '© Copyright 2027 QUANTUM COMPUTING & ENGINEERING SUMMIT.',
        email: 'quantumenginee@sciengasummits.com',
        accentColor: '#1e3a8a',
        accentGlow: 'rgba(30,58,138,0.35)',
    },
    icogwh: {
        conferenceId: 'icogwh',
        displayName: 'OBSTETRICS, GYNECOLOGY AND WOMEN HEALTH 2027',
        shortName: 'ICOGWH 2027',
        logoText: 'IC',
        logoSub: 'Summit',
        brandTop: 'ICOGWH',
        brandSub: 'SUMMIT 2027',
        footerText: '© Copyright 2027 ICOGWH SUMMIT.',
        email: 'obstetrics@sciengasummits.com',
        accentColor: '#e11d48',
        accentGlow: 'rgba(225,29,72,0.35)',
    },
    icemmae2027: {
        conferenceId: 'icemmae2027',
        displayName: 'MECHANICAL, MECHATRONICS AND AEROSPACE ENGINEERING 2027',
        shortName: 'ICEMMAE 2027',
        logoText: 'ME',
        logoSub: 'Summit',
        brandTop: 'ICEMMAE',
        brandSub: 'SUMMIT 2027',
        footerText: '© Copyright 2027 ICEMMAE SUMMIT.',
        email: 'icemmae@sciengasummits.com',
        accentColor: '#0369a1',
        accentGlow: 'rgba(3,105,161,0.35)',
    },
    polymat: {
        conferenceId: 'polymat',
        displayName: 'ANNUAL INTERNATIONAL CONFERENCE ON POLYMERS AND COMPOSITE MATERIALS 2026',
        shortName: 'POLYMAT SUMMIT 2026',
        logoText: 'PM',
        logoSub: 'Summit',
        brandTop: 'POLYMAT',
        brandSub: 'SUMMIT 2026',
        footerText: '© Copyright 2026 POLYMAT SUMMIT.',
        email: 'contact@polymatsummit.com',
        accentColor: '#3478DF',
        accentGlow: 'rgba(52,120,223,0.35)',
    },
    advancenano: {
        conferenceId: 'advancenano',
        displayName: 'ADVANCE NANO SUMMIT 2026',
        shortName: 'ADVANCE NANO SUMMIT',
        logoText: 'AN',
        logoSub: 'Summit',
        brandTop: 'ADVANCE NANO',
        brandSub: 'SUMMIT 2026',
        footerText: '© Copyright 2026 ADVANCE NANO SUMMIT.',
        email: 'advancenanosummit@sciengasummits.com',
        accentColor: '#1e3a8a',
        accentGlow: 'rgba(30,58,138,0.35)',
    },
    opticphoton: {
        conferenceId: 'opticphoton',
        displayName: 'OPTICS, PHOTONICS AND LASER TECHNOLOGY 2026',
        shortName: 'OPTIC PHOTON SUMMIT',
        logoText: 'OP',
        logoSub: 'Summit',
        brandTop: 'OPTIC PHOTON',
        brandSub: 'SUMMIT 2026',
        footerText: '© Copyright 2026 OPTIC PHOTON SUMMIT.',
        email: 'opticphotosummit@sciengasummits.com',
        accentColor: '#3478DF',
        accentGlow: 'rgba(52,120,223,0.35)',
    },
    cropscieng: {
        conferenceId: 'cropscieng',
        displayName: 'CROP SCIENCE AND ENGINEERING 2026',
        shortName: 'CROP SCIENCE SUMMIT',
        logoText: 'CS',
        logoSub: 'Summit',
        brandTop: 'CROP SCIENCE',
        brandSub: 'SUMMIT 2026',
        footerText: '© Copyright 2026 CROP SCIENCE SUMMIT.',
        email: 'cropsciengasummits@sciengasummits.com',
        accentColor: '#16a34a',
        accentGlow: 'rgba(22,163,74,0.35)',
    },
    cleaneng: {
        conferenceId: 'cleaneng',
        displayName: 'CLEAN ENERGY & SUSTAINABLE TECHNOLOGIES 2026',
        shortName: 'CLEAN ENERGY SUMMIT',
        logoText: 'CE',
        logoSub: 'Summit',
        brandTop: 'CLEAN ENERGY',
        brandSub: '& SUSTAINABLE TECH.',
        footerText: '© Copyright 2026 CLEAN ENERGY SUMMIT.',
        email: 'cleanengtech@sciengasummits.com',
        accentColor: '#10b981',
        accentGlow: 'rgba(16,185,129,0.35)',
    },
    healthmed: {
        conferenceId: 'healthmed',
        displayName: 'HEALTH MED SUMMIT 2026',
        shortName: 'HEALTH MED SUMMIT',
        logoText: 'HM',
        logoSub: 'Summit',
        brandTop: 'HEALTH & MEDICINE',
        brandSub: 'SUMMIT 2026',
        footerText: '© Copyright 2026 HEALTH & MEDICINE SUMMIT.',
        email: 'healthmedsummit@sciengasummits.com',
        accentColor: '#1e3a8a',
        accentGlow: 'rgba(30,58,138,0.35)',
    },
    astrospace: {
        conferenceId: 'astrospace',
        displayName: 'ASTRO SPACE SUMMIT 2026',
        shortName: 'ASTRO SPACE SUMMIT',
        logoText: 'AS',
        logoSub: 'Summit',
        brandTop: 'ASTRO SPACE',
        brandSub: 'SUMMIT 2026',
        footerText: '© Copyright 2026 ASTRO SPACE SUMMIT.',
        email: 'astrospace@sciengasummits.com',
        accentColor: '#6366f1',
        accentGlow: 'rgba(99,102,241,0.35)',
    },
    condensedphys: {
        conferenceId: 'condensedphys',
        displayName: 'CONDENSED MATTER PHYSICS SUMMIT 2026',
        shortName: 'CONDENSED PHYS SUMMIT',
        logoText: 'CP',
        logoSub: 'Summit',
        brandTop: 'CONDENSED PHYS',
        brandSub: 'SUMMIT 2026',
        footerText: '© Copyright 2026 CONDENSED MATTER PHYSICS SUMMIT.',
        email: 'condensedphyssummit2026@sciengasummits.com',
        accentColor: '#3b82f6',
        accentGlow: 'rgba(59,130,246,0.35)',
    },
    airobotsml: {
        conferenceId: 'airobotsml',
        displayName: 'AI ROBOTS & MACHINE LEARNING SUMMIT 2027',
        shortName: 'AI ROBOTS ML SUMMIT',
        logoText: 'AR',
        logoSub: 'Summit',
        brandTop: 'AI ROBOTS',
        brandSub: '& ML SUMMIT 2027',
        footerText: '© Copyright 2027 AI ROBOTS & MACHINE LEARNING SUMMIT.',
        email: 'airobotsml@sciengasummits.com',
        accentColor: '#4f46e5',
        accentGlow: 'rgba(79,70,229,0.35)',
    },
};
