// Conference accounts configuration
export const CONFERENCE_ACCOUNTS = [
    {
        username: 'LIUTEXSUMMIT2026',
        email: process.env.LIUTEX_EMAIL || 'liutex@sciengasummits.com',
        conferenceId: 'liutex',
        displayName: 'LIUTEX SUMMIT 2026',
    },
    {
        username: 'FOODAGRISUMMIT2026',
        email: process.env.FOODAGRI_EMAIL || 'foodagri@sciengasummits.com',
        conferenceId: 'foodagri',
        displayName: 'FOOD AGRI SUMMIT 2026',
    },
    {
        username: 'FLUIDMECHSUMMIT2026',
        email: process.env.FLUID_EMAIL || 'fluid@sciengasummits.com',
        conferenceId: 'fluid',
        displayName: 'FLUID MECHANICS & TURBOMACHINERY 2026',
    },
    {
        username: 'RENEWABLECLISUMMIT2026',
        email: process.env.RENEWABLE_EMAIL || 'renewable@sciengasummits.com',
        conferenceId: 'renewable',
        displayName: 'RENEWABLE ENERGY & CLIMATE CHANGE 2026',
    },
    {
        username: 'CYBERQUANTUMSUMMIT2026',
        email: process.env.CYBER_EMAIL || 'contact@cyberquantumsummit.com',
        conferenceId: 'cyber',
        displayName: 'CYBERSECURITY & QUANTUM COMPUTING 2026',
    },
    {
        username: 'POWERENGSUMMIT2026',
        email: process.env.POWERENG_EMAIL || 'powerenergy@sciengasummits.com',
        conferenceId: 'powereng',
        displayName: 'POWER ENERGY & ELECTRICAL ENGINEERING 2026',
    },
    {
        username: 'CIVILENVSUMMIT2026',
        email: process.env.CIVILENV_EMAIL || 'civil@sciengasummits.com',
        conferenceId: 'civilenv',
        displayName: 'CIVIL, ENVIRONMENTAL & ARCHITECTURAL ENGINEERING 2026',
    },
    {
        username: 'IQCE2027',
        email: process.env.IQCE2027_EMAIL || process.env.IQCES_EMAIL || 'quantumengineering@sciengasummits.com',
        conferenceId: 'iqce2027',
        displayName: 'QUANTUM COMPUTING & ENGINEERING SUMMIT 2027',
    },
    {
        username: 'ICOGWHSUMMIT2027',
        email: process.env.ICOGWH_EMAIL || 'obstetrics@sciengasummits.com',
        conferenceId: 'icogwh',
        displayName: 'OBSTETRICS, GYNECOLOGY AND WOMEN HEALTH 2027',
    },
    {
        username: 'ICEMMAE2027',
        email: process.env.ICEMMAE_EMAIL || 'icemmae@sciengasummits.com',
        conferenceId: 'icemmae2027',
        displayName: 'MECHANICAL, MECHATRONICS AND AEROSPACE ENGINEERING 2027',
    },
    {
        username: 'POLYMATSUMMIT2026',
        email: process.env.POLYMAT_EMAIL || 'contact@polymatsummit.com',
        conferenceId: 'polymat',
        displayName: 'ANNUAL INTERNATIONAL CONFERENCE ON POLYMERS AND COMPOSITE MATERIALS 2026',
    },
    {
        username: 'ASTROSPACESUMMIT2026',
        email: process.env.ASTRO_EMAIL || 'astrospace@sciengasummits.com',
        conferenceId: 'astrospace',
        displayName: 'ASTRONOMY, ASTROPHYSICS AND SPACE SCIENCE 2026',
    },
    {
        username: 'CONDENSEDPHYSSUMMIT2026',
        email: process.env.CONDENSEDPHYS_EMAIL || 'condensedphy@sciengasummits.com',
        conferenceId: 'condensedphys',
        displayName: 'CONDENSED MATTER & APPLIED PHYSICS SUMMIT 2027',
    },
    {
        username: 'AIROBOTSMLSUMMIT2026',
        email: process.env.AIROBOTSML_EMAIL || 'airobotsml@sciengasummits.com',
        conferenceId: 'airobotsml',
        displayName: 'ARTIFICIAL INTELLIGENCE, ROBOTICS AND MACHINE LEARNING 2026',
    },
];

// Conference config for frontend
export const CONFERENCE_CONFIG = {
    liutex: {
        conferenceId: 'liutex',
        displayName: 'LIUTEX VORTEX SUMMIT 2026',
        shortName: 'LIUTEX SUMMIT',
        logoText: 'LV',
        logoSub: 'Summit',
        brandTop: 'LIUTEX',
        brandSub: 'VORTEX SUMMIT',
        footerText: '© Copyright 2026 LIUTEX SUMMIT.',
        email: 'liutex@sciengasummits.com',
        accentColor: '#6366f1',
        accentGlow: 'rgba(99,102,241,0.35)',
    },
    foodagri: {
        conferenceId: 'foodagri',
        displayName: 'FOOD AGRI SUMMIT 2026',
        shortName: 'FOOD AGRI SUMMIT',
        logoText: 'FA',
        logoSub: 'Summit',
        brandTop: 'FOOD AGRI',
        brandSub: 'SUMMIT 2026',
        footerText: '© Copyright 2026 FOOD AGRI SUMMIT.',
        email: 'foodagri@sciengasummits.com',
        accentColor: '#16a34a',
        accentGlow: 'rgba(22,163,74,0.35)',
    },
    fluid: {
        conferenceId: 'fluid',
        displayName: 'FLUID MECHANICS & TURBOMACHINERY 2026',
        shortName: 'FLUID SUMMIT',
        logoText: 'FM',
        logoSub: 'Summit',
        brandTop: 'FLUID MECHANICS',
        brandSub: '& TURBOMACHINERY',
        footerText: '© Copyright 2026 FLUID MECHANICS & TURBOMACHINERY SUMMIT.',
        email: 'fluid@sciengasummits.com',
        accentColor: '#0891b2',
        accentGlow: 'rgba(8,145,178,0.35)',
    },
    renewable: {
        conferenceId: 'renewable',
        displayName: 'RENEWABLE ENERGY & CLIMATE CHANGE 2026',
        shortName: 'RENEWABLE CLI SUMMIT',
        logoText: 'RE',
        logoSub: 'Summit',
        brandTop: 'RENEWABLE ENERGY',
        brandSub: '& CLIMATE CHANGE',
        footerText: '© Copyright 2026 RENEWABLE ENERGY & CLIMATE CHANGE SUMMIT.',
        email: 'renewable@sciengasummits.com',
        accentColor: '#16a34a',
        accentGlow: 'rgba(22,163,74,0.35)',
    },
    cyber: {
        conferenceId: 'cyber',
        displayName: 'CYBERSECURITY & QUANTUM COMPUTING 2026',
        shortName: 'CYBERQUANTUM SUMMIT',
        logoText: 'CQ',
        logoSub: 'Summit',
        brandTop: 'CYBERQUANTUM',
        brandSub: 'SUMMIT 2026',
        footerText: '© Copyright 2026 CYBERQUANTUM SUMMIT.',
        email: 'contact@cyberquantumsummit.com',
        accentColor: '#2563eb',
        accentGlow: 'rgba(37,99,235,0.35)',
    },
    powereng: {
        conferenceId: 'powereng',
        displayName: 'POWER ENERGY & ELECTRICAL ENGINEERING 2026',
        shortName: 'POWERENG SUMMIT',
        logoText: 'PE',
        logoSub: 'Summit',
        brandTop: 'POWER ENERGY',
        brandSub: '& ELECTRICAL ENG.',
        footerText: '© Copyright 2026 POWER ENERGY & ELECTRICAL ENGINEERING SUMMIT.',
        email: 'powerenergy@sciengasummits.com',
        accentColor: '#d97706',
        accentGlow: 'rgba(217,119,6,0.35)',
    },
    civilenv: {
        conferenceId: 'civilenv',
        displayName: 'CIVIL, ENVIRONMENTAL & ARCHITECTURAL ENGINEERING 2026',
        shortName: 'CIVILENV SUMMIT',
        logoText: 'CE',
        logoSub: 'Summit',
        brandTop: 'CIVIL, ENVIRONMENTAL',
        brandSub: '& ARCHITECTURAL ENG.',
        footerText: '© Copyright 2026 CIVIL, ENVIRONMENTAL & ARCHITECTURAL ENGINEERING SUMMIT.',
        email: 'civil@sciengasummits.com',
        accentColor: '#059669',
        accentGlow: 'rgba(5,150,105,0.35)',
    },
    iqce2027: {
        conferenceId: 'iqce2027',
        displayName: 'QUANTUM COMPUTING & ENGINEERING SUMMIT 2027',
        shortName: 'IQCE 2027',
        logoText: 'QC',
        logoSub: 'Summit',
        brandTop: 'QUANTUM COMPUTING',
        brandSub: '& ENGINEERING 2027',
        footerText: '© Copyright 2027 QUANTUM COMPUTING & ENGINEERING SUMMIT.',
        email: 'quantumenginee@sciengasummits.com',
        accentColor: '#1e3a8a',
        accentGlow: 'rgba(30,58,138,0.35)',
    },
    icogwh: {
        conferenceId: 'icogwh',
        displayName: 'OBSTETRICS, GYNECOLOGY AND WOMEN HEALTH 2027',
        shortName: 'ICOGWH 2027',
        logoText: 'IC',
        logoSub: 'Summit',
        brandTop: 'ICOGWH',
        brandSub: 'SUMMIT 2027',
        footerText: '© Copyright 2027 ICOGWH SUMMIT.',
        email: 'obstetrics@sciengasummits.com',
        accentColor: '#e11d48',
        accentGlow: 'rgba(225,29,72,0.35)',
    },
    icemmae2027: {
        conferenceId: 'icemmae2027',
        displayName: 'MECHANICAL, MECHATRONICS AND AEROSPACE ENGINEERING 2027',
        shortName: 'ICEMMAE 2027',
        logoText: 'ME',
        logoSub: 'Summit',
        brandTop: 'ICEMMAE',
        brandSub: 'SUMMIT 2027',
        footerText: '© Copyright 2027 ICEMMAE SUMMIT.',
        email: 'icemmae@sciengasummits.com',
        accentColor: '#0369a1',
        accentGlow: 'rgba(3,105,161,0.35)',
    },
    astrospace: {
        conferenceId: 'astrospace',
        displayName: 'ASTRONOMY, ASTROPHYSICS AND SPACE SCIENCE 2026',
        shortName: 'ASTROSPACESUMMIT 2026',
        logoText: 'AS',
        logoSub: 'Summit',
        brandTop: 'ASTROSPACE',
        brandSub: 'SUMMIT 2026',
        footerText: '© Copyright 2026 ASTROSPACESUMMIT.',
        email: 'astrospace@sciengasummits.com',
        accentColor: '#7c3aed',
        accentGlow: 'rgba(124,58,237,0.35)',
    },
    condensedphys: {
        conferenceId: 'condensedphys',
        displayName: 'CONDENSED MATTER & APPLIED PHYSICS SUMMIT 2027',
        shortName: 'CONDENSEDPHYSSUMMIT 2027',
        logoText: 'CP',
        logoSub: 'Summit',
        brandTop: 'CONDENSEDPHYS',
        brandSub: 'SUMMIT 2027',
        footerText: '© Copyright 2027 CONDENSEDPHYSSUMMIT.',
        email: 'condensedphy@sciengasummits.com',
        accentColor: '#001F3F',
        accentGlow: 'rgba(0,31,63,0.35)',
    },
    airobotsml: {
        conferenceId: 'airobotsml',
        displayName: 'ARTIFICIAL INTELLIGENCE, ROBOTICS AND MACHINE LEARNING 2026',
        shortName: 'AI ROBOTS ML 2026',
        logoText: 'AI',
        logoSub: 'Summit',
        brandTop: 'AI ROBOTS',
        brandSub: '& MACHINE LEARNING',
        footerText: '© Copyright 2026 AI ROBOTS ML SUMMIT.',
        email: 'airobotsml@sciengasummits.com',
        accentColor: '#0ea5e9',
        accentGlow: 'rgba(14,165,233,0.35)',
    },
};
